name: Auto Deploy TEST

on:
  push:
    branches:
      - 'main'

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 깃 허브 체크아웃
      uses: actions/checkout@v2

    - name: 서버 세팅
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 서버 접속 및 배포.
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USER }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        port: 22
        script: |
          ls
          cd puru-puru-BE/
          git stash
          git pull origin main
          npm install
          tsc > tsc.log 2>&1
          cd ..
          cd puru-puru-BE/
          pm2 delete 0
          pm2 start app.js > pm2.log 2>&1
