name: 깃허브 액션 테스트.

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      REGION: ${{ secrets.REGION }}
      ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      ACL_OPTIONS: ${{ secrets.ACL_OPTIONS }}
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_TESTDB: ${{ secrets.MYSQL_TESTDB }}
      PORT: ${{ secrets.PORT }}
      JWT_ACCESS_SECRET_KEY: ${{ secrets.JWT_ACCESS_SECRET_KEY }}
      JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
      MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
      BCRYPT_SALT: ${{ secrets.BCRYPT_SALT }}

    steps:
    - name: 저장소 체크아웃.
      uses: actions/checkout@v2

    - name: 노드 설정.
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 의존성 설치.
      run: npm install

    - name: 빌드.
      run: npm run build

    - name: 이후 테스트.
      run: npm test
