name: 깃허브 액션 테스트.

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 저장소 체크아웃.
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: 의존성 설치.
      run: npm install

    - name: 빌드.
      run: npm run build

    - name: 이후 테스트.
      run: npm test
